# Generated by Django 6.0.3 on 2026-03-03 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('Etudiant', 'Etudiant'), ('Professeur', 'Professeur'), ('Administrateur', 'Administrateur')], max_length=20)),
                ('est_actif', models.BooleanField(default=False)),
            ],
        ),
    ]
