# Generated by Django 6.0.3 on 2026-03-03 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Utilisateur',
        ),
    ]
