# Generated by Django 6.0.3 on 2026-03-03 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0002_rename_user_utilisateur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='role',
            field=models.CharField(choices=[('etudiant', 'etudiant'), ('professeur', 'professeur'), ('administrateur', 'administrateur')], max_length=20),
        ),
    ]
