# Generated by Django 6.0.3 on 2026-03-03 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0004_projet_collaborateur_tache'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='matricule',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='prenom',
            field=models.CharField(default='Inconnu', max_length=255),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='promotion',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='telephone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='tache',
            name='statut',
            field=models.CharField(choices=[('a_faire', 'A faire'), ('termine', 'Terminé')], default='a_faire', max_length=20),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='role',
            field=models.CharField(choices=[('etudiant', 'Etudiant'), ('professeur', 'Professeur'), ('administrateur', 'Administrateur')], max_length=20),
        ),
    ]
