# Generated by Django 6.0.3 on 2026-03-09 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0006_alter_utilisateur_options_alter_utilisateur_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tache',
            name='date_echeance',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
