# Generated by Django 6.0.3 on 2026-03-09 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0007_alter_tache_date_echeance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tache',
            name='date_completion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
