# Generated by Django 6.0.3 on 2026-03-11 20:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0009_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='DerniereLecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_lecture', models.DateTimeField(auto_now=True)),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dernieres_lectures', to='backend_app.projet')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dernieres_lectures', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'projet')},
            },
        ),
    ]
